# Generated by Django 3.2.12 on 2023-07-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_outputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputfile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
